name: mixvy
description: "MixVy — Meet. Connect. Vibe. Live audio/video rooms."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.11.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_functions: ^6.0.4
  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  meta: ^1.17.0
  agora_rtc_engine: ^6.5.3
  uuid: ^4.3.0
  image_picker: ^1.0.7
  image: ^4.0.0
  collection: ^1.19.1
  firebase_auth: ^6.2.0
  firebase_database: ^12.2.0
  connectivity_plus: ^7.0.0
  firebase_core: ^4.5.0
  firebase_messaging: ^16.0.3
  firebase_storage: ^13.0.3
  path_provider: ^2.1.2
  cloud_firestore: ^6.1.3
  firebase_analytics: ^12.1.3
  firebase_remote_config: ^6.1.0
  flutter_stripe: ^12.4.0
  flutter_riverpod: 2.4.0
  freezed_annotation: ^3.1.0
  http: ^1.1.0
  flutter_dotenv: ^6.0.0
  share_plus: ^13.1.0
  firebase_crashlytics: ^5.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  google_sign_in: ^7.2.0
  logging: ^1.2.0
  package_info_plus: ^10.1.0
  path: ^1.9.1
  flutter_webrtc: ^1.4.1
  web: any
  cached_network_image: ^3.4.1
  google_fonts: ^8.0.2
  crypto: ^3.0.3
  rxdart: ^0.28.0
  json_annotation: ^4.11.0
  riverpod: 2.4.0
  # state_notifier has been removed

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.14.0
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  mocktail: ^1.0.0
  fake_cloud_firestore: ^4.1.0+1
  flutter_launcher_icons: ^0.14.1
  patrol: ^4.3.0
  firebase_core_platform_interface: any
flutter:
  assets:
    - assets/images/
    - assets/images/branding/
    - assets/icons/
    - assets/fonts/
    - assets/env/
    - assets/.env
    - assets/emojis/
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansSymbols
      fonts:
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf
    - family: NotoSansSymbols2
      fonts:
        - asset: assets/fonts/NotoSansSymbols2-Regular.ttf
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/branding/mixvy_logo.png"
  web:
    generate: true
    image_path: "assets/images/branding/mixvy_logo.png"
    background_color: "#0B0B0B"
    theme_color: "#D4AF37"
  windows:
    generate: true
    image_path: "assets/images/branding/mixvy_logo.png"
    icon_size: 48

