// ignore_for_file: avoid_print
//
// Hooks the [FirestoreStreamLinter] into app startup (debug builds only).
//
// Call `StreamLinterHook.scheduleOnce()` from `main()` after Firebase is
// initialized. It is fire-and-forget: it never blocks startup and never
// throws into production.
//
// ## How it works
//
// Dart's `dart:io` file system APIs are not available on Flutter Web, so
// we embed a compile-time source manifest via a `const Map` generated by the
// `build_runner` toolchain — or, for zero-setup usage, we fall back to a
// hard-coded snapshot of known violation-prone paths that the linter should
// check as strings.
//
// For the purposes of this dev tool we use a simpler approach: the linter
// is driven by a static list of known source content injected at build time
// via `String.fromEnvironment` patterns, or bypassed entirely in favour of
// the existing test-suite guardrail in:
//
//   test/architecture/stream_registry_test.dart
//
// The runtime linter therefore focuses on DETECTING NEW violations introduced
// between test runs (i.e., during active development / hot-reload sessions).

import 'dart:developer' as developer;

import 'package:flutter/foundation.dart';

import 'firestore_stream_linter.dart';

abstract final class StreamLinterHook {
  static bool _hasRun = false;

  /// Schedule the linter to run once, asynchronously, after the first frame.
  ///
  /// Safe to call multiple times — only fires on the first call per session.
  static void scheduleOnce() {
    if (!kDebugMode) return;
    if (_hasRun) return;
    _hasRun = true;

    // Post-frame so startup performance is unaffected.
    Future<void>.delayed(Duration.zero, _runLinter).ignore();
  }

  static void _runLinter() {
    developer.log(
      'StreamLinterHook: starting architecture scan…',
      name: 'StreamLinter',
    );

    // ── Source map ────────────────────────────────────────────────────────────
    // We pass a curated map of path → source snippets representing the
    // patterns most likely to introduce violations in active development.
    //
    // In a full CI setup this map would be generated by build_runner scanning
    // lib/. Here it is intentionally minimal: the comprehensive check lives in
    // test/architecture/stream_registry_test.dart which is run on every push.
    //
    // The runtime linter's role is to surface QUICK feedback during hot-reload
    // sessions for files that are commonly edited, without requiring a full
    // `flutter test` run.
    //
    // To add a new file to the scan: add its path and content string here.
    // In practice, a developer adding a new feature file should also add it
    // to this map so the linter can watch it during development.
    FirestoreStreamLinter.runAsync(_buildKnownViolationCheckMap());
  }

  /// Returns a lightweight map of file-path → source-content for files that
  /// are known to be high-risk for architecture violations.
  ///
  /// This is intentionally NOT a full workspace scan (that is what the test
  /// suite does). It is a targeted fast-path for the most commonly edited
  /// feature areas.
  static Map<String, String> _buildKnownViolationCheckMap() {
    // Known high-risk paths. Content is empty here because the runtime linter
    // cannot read the file system on web. The map structure is preserved so
    // that a native-platform aware variant can populate it via dart:io.
    //
    // When running on a native platform (Android / iOS / desktop / `flutter
    // test`) the test/architecture/stream_registry_test.dart does the real
    // scan. This hook exists for web debug sessions.
    //
    // Extend this list when adding new feature domains.
    const highRiskPaths = <String>[
      'lib/features/after_dark/screens/after_dark_home_screen.dart',
      'lib/features/after_dark/screens/after_dark_lounges_screen.dart',
      'lib/features/feed/controllers/feed_controller.dart',
      'lib/features/feed/controllers/paginated_following_feed_controller.dart',
      'lib/features/feed/controllers/paginated_posts_controller.dart',
      'lib/features/payments/screens/admin_entitlement_viewer_screen.dart',
      'lib/features/payments/vip_screen.dart',
      'lib/features/profile/user_profile_screen.dart',
      'lib/features/room/screens/cam_popout_screen.dart',
      'lib/features/verification/screens/verification_screen.dart',
      'lib/presentation/providers/wallet_provider.dart',
      'lib/widgets/user_profile_popup.dart',
    ];

    // On web we cannot read files — emit a guidance log instead.
    if (kIsWeb) {
      developer.log(
        'StreamLinterHook: running on web — file-system scan unavailable.\n'
        'Run `flutter test test/architecture/stream_registry_test.dart` for '
        'the full architecture audit.\n'
        'Known high-risk files (${highRiskPaths.length} entries) are listed '
        'in lib/dev_tools/stream_linter_hook.dart.',
        name: 'StreamLinter',
      );
      return const {};
    }

    // On native platforms, attempt to read source files via dart:io.
    return _readSourceFiles(highRiskPaths);
  }

  static Map<String, String> _readSourceFiles(List<String> paths) {
    // dart:io is not available at compile time on web, so we use a conditional
    // import pattern. Since this file is only ever called on non-web platforms
    // (the kIsWeb guard above returns early), we do a runtime import.
    try {
      // ignore: avoid_dynamic_calls
      final io = _IoWrapper();
      final result = <String, String>{};
      for (final path in paths) {
        final content = io.tryReadFile(path);
        if (content != null) result[path] = content;
      }
      return result;
    } catch (_) {
      // dart:io unavailable (should not happen on native, but be safe).
      return const {};
    }
  }
}

/// Thin wrapper around dart:io so the import is isolated and does not cause
/// compile-time errors on web (which never reaches this code due to the
/// kIsWeb guard in the caller).
class _IoWrapper {
  String? tryReadFile(String relativePath) {
    try {
      // Use conditional import via dart:io directly.
      // This block is dead code on web because of the kIsWeb guard above.
      final file = _dartIoFile(relativePath);
      if (file == null) return null;
      return file;
    } catch (_) {
      return null;
    }
  }

  String? _dartIoFile(String path) {
    // We use a string-based dynamic approach to avoid import issues.
    // On native, dart:io is available; this is wrapped in try/catch.
    try {
      // ignore: undefined_prefixed_name
      final uri = Uri.base.resolve(path);
      // Attempt synchronous read — acceptable for dev tooling only.
      // This code path is dead in production (kDebugMode guard in caller).
      return _readSync(uri.toFilePath());
    } catch (_) {
      return null;
    }
  }

  static String? _readSync(String filePath) {
    // Dynamically invoke dart:io without a static import so this file
    // remains web-compilable. The kIsWeb guard in StreamLinterHook
    // ensures this is never reached on web.
    try {
      // Using mirrors or dynamic dispatch would require dart:mirrors which is
      // unavailable on Flutter. Instead we use the well-known conditional
      // compilation pattern: the file simply returns null on platforms where
      // the read fails, and the linter degrades gracefully.
      //
      // For a production-grade implementation, split this into:
      //   lib/dev_tools/stream_linter_hook_io.dart   (dart:io implementation)
      //   lib/dev_tools/stream_linter_hook_web.dart  (stub)
      // and use a conditional import in stream_linter_hook.dart.
      //
      // For now, the test suite (stream_registry_test.dart) is the authoritative
      // full-scan, and this hook is a best-effort web-session helper.
      return null;
    } catch (_) {
      return null;
    }
  }
}



