import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mixvy/shared/models/room.dart';
import '../services/category_service.dart';
import '../services/room_service.dart';

/// Controller for room creation with tag normalization and category classification.
class RoomCreationController {
  final RoomService _roomService;
  final CategoryService _categoryService;

  RoomCreationController({
    required RoomService roomService,
    required CategoryService categoryService,
  })  : _roomService = roomService,
        _categoryService = categoryService;

  /// Creates a room with user-entered tags.
  ///
  /// Normalizes tags and computes category automatically.
  Future<Room> createRoom({
    required String title,
    required String description,
    required String hostId,
    required List<String> tags,
    bool isLive = false,
  }) async {
    // Validate inputs
    if (title.trim().isEmpty) {
      throw ArgumentError('Title cannot be empty');
    }

    if (description.trim().isEmpty) {
      throw ArgumentError('Description cannot be empty');
    }

    if (hostId.trim().isEmpty) {
      throw ArgumentError('Host ID cannot be empty');
    }

    // Normalize tags
    final normalizedTags = _categoryService.normalizeTags(tags);

    // Validate tags
    final validationError = _categoryService.validateTags(normalizedTags);
    if (validationError != null) {
      throw ArgumentError(validationError);
    }

    // Classify room based on tags
    final category = _categoryService.classifyRoom(normalizedTags);

    // Create room object
    final room = Room(
      id: '', // Will be generated by Firestore
      title: title.trim(),
      description: description.trim(),
      hostId: hostId.trim(),
      tags: normalizedTags,
      category: category,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isLive: isLive,
      viewerCount: 0,
    );

    // Save to Firestore
    return await _roomService.createRoom(room);
  }

  /// Updates an existing room with new tags.
  ///
  /// Recomputes category if tags have changed.
  Future<void> updateRoom({
    required Room room,
    List<String>? newTags,
    String? newTitle,
    String? newDescription,
    bool? newIsLive,
  }) async {
    if (room.id.isEmpty) {
      throw ArgumentError('Room ID cannot be empty');
    }

    // Prepare updated tags
    final tagsToUse = newTags ?? room.tags;
    final normalizedTags = _categoryService.normalizeTags(tagsToUse);

    // Validate tags
    final validationError = _categoryService.validateTags(normalizedTags);
    if (validationError != null) {
      throw ArgumentError(validationError);
    }

    // Recompute category
    final category = _categoryService.classifyRoom(normalizedTags);

    // Create updated room
    final updatedRoom = room.copyWith(
      title: newTitle?.trim() ?? room.title,
      description: newDescription?.trim() ?? room.description,
      tags: normalizedTags,
      category: category,
      isLive: newIsLive ?? room.isLive,
    );

    // Save to Firestore
    await _roomService.updateRoom(updatedRoom);
  }

  /// Validates tags without creating a room.
  ///
  /// Returns null if valid, otherwise returns error message.
  String? validateTags(List<String> tags) {
    final normalized = _categoryService.normalizeTags(tags);
    return _categoryService.validateTags(normalized);
  }

  /// Normalizes tags for preview before submission.
  List<String> normalizeTags(List<String> tags) {
    return _categoryService.normalizeTags(tags);
  }

  /// Classifies tags to show predicted category.
  String classifyTags(List<String> tags) {
    final normalized = _categoryService.normalizeTags(tags);
    return _categoryService.classifyRoom(normalized);
  }

  /// Suggests a category based on partial tag input.
  String? suggestCategory(String partialTag) {
    return _categoryService.suggestCategory(partialTag);
  }

  /// Gets all available categories.
  List<String> getAllCategories() {
    return _categoryService.getAllCategories();
  }

  /// Gets keywords for a specific category.
  List<String> getCategoryKeywords(String category) {
    return _categoryService.getCategoryKeywords(category);
  }
}

/// Provider for RoomCreationController
final roomCreationControllerProvider = Provider<RoomCreationController>((ref) {
  final roomService = RoomService();
  final categoryService = CategoryService();

  return RoomCreationController(
    roomService: roomService,
    categoryService: categoryService,
  );
});

