// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBmz9ybuDRCA2dAVjFZVj7R7wrDL0wTYU',
    appId: '1:980846719834:web:4f26d018877528c3077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    measurementId: 'G-DRXWK1PPEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbS7zVY2o4S1-OOPkqFuUXz5B5hmmsS0U',
    appId: '1:980846719834:android:c369e5b790a2945b077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15xj5jE4UtiLoidJ4QmpJr47ZxdY6AQk',
    appId: '1:980846719834:ios:ec445d70ccc6c131077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    androidClientId:
        '980846719834-2n0h54hq88s6gra5qnvqsbnh3ebnedcb.apps.googleusercontent.com',
    iosClientId:
        '980846719834-hsn70r4kaghfit4d6t1keohuvjfho9v9.apps.googleusercontent.com',
    iosBundleId: 'com.mixvy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBmz9ybuDRCA2dAVjFZVj7R7wrDL0wTYU',
    appId: '1:980846719834:web:faa83926491c9adb077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    measurementId: 'G-L0G075C2EZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmz9ybuDRCA2dAVjFZVj7R7wrDL0wTYU',
    appId: '1:980846719834:web:faa83926491c9adb077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    measurementId: 'G-L0G075C2EZ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBBmz9ybuDRCA2dAVjFZVj7R7wrDL0wTYU',
    appId: '1:980846719834:web:faa83926491c9adb077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    measurementId: 'G-L0G075C2EZ',
  );
}



