// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6_Eye8JMEW7dXFpo-i-Frp4t3owyh_I',
    appId: '1:770164332233:web:ae8bae1c4c68b525c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    authDomain: 'mixvy-v2.firebaseapp.com',
    storageBucket: 'mixvy-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCejcBAOY6WPsc4qfVkmOvnx6MOofFiJo4',
    appId: '1:770164332233:android:e4c4e6e673c54bbbc3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    storageBucket: 'mixvy-v2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2FRIhjf7Z7-OROQXjHMq08lhI9lY0Rtg',
    appId: '1:770164332233:ios:e088231cb0898607c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    storageBucket: 'mixvy-v2.firebasestorage.app',
    iosBundleId: 'com.mixandmingle.mixAndMingle',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2FRIhjf7Z7-OROQXjHMq08lhI9lY0Rtg',
    appId: '1:770164332233:ios:e088231cb0898607c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    storageBucket: 'mixvy-v2.firebasestorage.app',
    iosBundleId: 'com.mixandmingle.mixAndMingle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6_Eye8JMEW7dXFpo-i-Frp4t3owyh_I',
    appId: '1:770164332233:web:153750240deaa27dc3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    authDomain: 'mixvy-v2.firebaseapp.com',
    storageBucket: 'mixvy-v2.firebasestorage.app',
  );
}
