// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6_Eye8JMEW7dXFpo-i-Frp4t3owyh_I',
    appId: '1:770164332233:web:ae8bae1c4c68b525c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    authDomain: 'mixvy-v2.firebaseapp.com',
    storageBucket: 'mixvy-v2.firebasestorage.app',
    measurementId: 'G-DRXWK1PPEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCejcBAOY6WPsc4qfVkmOvnx6MOofFiJo4',
    appId: '1:770164332233:android:8fae7410889374d9c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    storageBucket: 'mixvy-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2FRIhjf7Z7-OROQXjHMq08lhI9lY0Rtg',
    appId: '1:770164332233:ios:056a1477bcfa5f44c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    storageBucket: 'mixvy-v2.firebasestorage.app',
    androidClientId:
        '980846719834-2n0h54hq88s6gra5qnvqsbnh3ebnedcb.apps.googleusercontent.com',
    iosClientId:
        '980846719834-hsn70r4kaghfit4d6t1keohuvjfho9v9.apps.googleusercontent.com',
    iosBundleId: 'com.mixvy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6_Eye8JMEW7dXFpo-i-Frp4t3owyh_I',
    appId: '1:770164332233:web:153750240deaa27dc3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    authDomain: 'mixvy-v2.firebaseapp.com',
    storageBucket: 'mixvy-v2.firebasestorage.app',
    measurementId: 'G-L0G075C2EZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM6_Eye8JMEW7dXFpo-i-Frp4t3owyh_I',
    appId: '1:770164332233:web:ae8bae1c4c68b525c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    authDomain: 'mixvy-v2.firebaseapp.com',
    storageBucket: 'mixvy-v2.firebasestorage.app',
    measurementId: 'G-L0G075C2EZ',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCM6_Eye8JMEW7dXFpo-i-Frp4t3owyh_I',
    appId: '1:770164332233:web:ae8bae1c4c68b525c3df18',
    messagingSenderId: '770164332233',
    projectId: 'mixvy-v2',
    authDomain: 'mixvy-v2.firebaseapp.com',
    storageBucket: 'mixvy-v2.firebasestorage.app',
    measurementId: 'G-L0G075C2EZ',
  );
}



