// ignore_for_file: lines_longer_than_80_chars
import 'emoji_pack_item.dart';

/// The full 100-item emoji / GIF pack.
///
/// Asset paths (assets/emojis/…) are placeholders — replace the PNG files
/// with your actual artwork.
///
/// GIF URLs use the Giphy media format:
///   https://media.giphy.com/media/{id}/giphy.gif
/// Replace the placeholder IDs with real Giphy media IDs before shipping.
class EmojiPackCatalog {
  EmojiPackCatalog._();

  static const List<EmojiPackItem> all = [
    // ── Flirty (18+) ────────────────────────────────────────────────────────
    EmojiPackItem(
      id: 'f_01',
      name: 'Smirk',
      category: EmojiCategory.flirty,
      tags: ['flirty', 'cheeky'],
      path: 'assets/emojis/flirty/smirk.png',
    ),
    EmojiPackItem(
      id: 'f_02',
      name: 'Devil Grin',
      category: EmojiCategory.flirty,
      tags: ['flirty', 'naughty'],
      path: 'assets/emojis/flirty/devil_grin.png',
    ),
    EmojiPackItem(
      id: 'f_03',
      name: 'Side-eye',
      category: EmojiCategory.flirty,
      tags: ['flirty', 'sly'],
      path: 'assets/emojis/flirty/side_eye.png',
    ),
    EmojiPackItem(
      id: 'f_04',
      name: 'Splash Oops',
      category: EmojiCategory.flirty,
      tags: ['flirty', 'funny'],
      gifQuery: 'oops splash funny',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'f_05',
      name: 'Peach Pop',
      category: EmojiCategory.flirty,
      tags: ['flirty', 'innuendo'],
      path: 'assets/emojis/flirty/peach.png',
    ),
    EmojiPackItem(
      id: 'f_06',
      name: 'Eggplant Wink',
      category: EmojiCategory.flirty,
      tags: ['flirty', 'innuendo'],
      path: 'assets/emojis/flirty/eggplant.png',
    ),
    EmojiPackItem(
      id: 'f_07',
      name: 'Tongue Out',
      category: EmojiCategory.flirty,
      tags: ['cheeky', 'funny'],
      path: 'assets/emojis/flirty/tongue_out.png',
    ),
    EmojiPackItem(
      id: 'f_08',
      name: 'Kiss Mark',
      category: EmojiCategory.flirty,
      tags: ['flirty', 'romantic'],
      gifQuery: 'kiss mark cartoon',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'f_09',
      name: 'Blush Sweat',
      category: EmojiCategory.flirty,
      tags: ['embarrassed', 'cute'],
      path: 'assets/emojis/flirty/blush.png',
    ),
    EmojiPackItem(
      id: 'f_10',
      name: 'Hand Giggle',
      category: EmojiCategory.flirty,
      tags: ['laugh', 'cheeky'],
      path: 'assets/emojis/flirty/hand_giggle.png',
    ),
    EmojiPackItem(
      id: 'f_11',
      name: 'Wink',
      category: EmojiCategory.flirty,
      tags: ['flirt', 'cheeky'],
      path: 'assets/emojis/flirty/wink.png',
    ),
    EmojiPackItem(
      id: 'f_12',
      name: 'Eyebrow Raise',
      category: EmojiCategory.flirty,
      tags: ['flirt', 'mischievous'],
      path: 'assets/emojis/flirty/eyebrow_raise.png',
    ),
    EmojiPackItem(
      id: 'f_13',
      name: 'Heart Eyes',
      category: EmojiCategory.flirty,
      tags: ['love', 'crush'],
      path: 'assets/emojis/flirty/heart_eyes.png',
    ),
    EmojiPackItem(
      id: 'f_14',
      name: 'Cat Wink',
      category: EmojiCategory.flirty,
      tags: ['flirt', 'funny'],
      path: 'assets/emojis/flirty/cat_wink.png',
    ),
    EmojiPackItem(
      id: 'f_15',
      name: 'Lip Bite',
      category: EmojiCategory.flirty,
      tags: ['flirt', 'tease'],
      path: 'assets/emojis/flirty/lip_bite.png',
    ),
    EmojiPackItem(
      id: 'f_16',
      name: 'Blowing Kiss',
      category: EmojiCategory.flirty,
      tags: ['flirt', 'romantic'],
      gifQuery: 'blowing kiss cute',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'f_17',
      name: 'Cheek Squeeze',
      category: EmojiCategory.flirty,
      tags: ['cute', 'playful'],
      path: 'assets/emojis/flirty/cheek_squeeze.png',
    ),
    EmojiPackItem(
      id: 'f_18',
      name: 'Naughty Grin',
      category: EmojiCategory.flirty,
      tags: ['mischievous', 'flirt'],
      path: 'assets/emojis/flirty/naughty_grin.png',
    ),
    EmojiPackItem(
      id: 'f_19',
      name: 'Peek-a-boo',
      category: EmojiCategory.flirty,
      tags: ['shy', 'playful'],
      path: 'assets/emojis/flirty/peek_a_boo.png',
    ),
    EmojiPackItem(
      id: 'f_20',
      name: 'Tongue Wink',
      category: EmojiCategory.flirty,
      tags: ['cheeky', 'naughty'],
      path: 'assets/emojis/flirty/tongue_wink.png',
    ),

    // ── Party ────────────────────────────────────────────────────────────────
    EmojiPackItem(
      id: 'p_01',
      name: 'Party Pop',
      category: EmojiCategory.party,
      tags: ['party', 'celebration'],
      gifQuery: 'party confetti pop',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'p_02',
      name: 'Dance Move',
      category: EmojiCategory.party,
      tags: ['dance', 'funny'],
      path: 'assets/emojis/party/dance_move.png',
    ),
    EmojiPackItem(
      id: 'p_03',
      name: 'Disco Ball Spin',
      category: EmojiCategory.party,
      tags: ['party', 'fun'],
      path: 'assets/emojis/party/disco_ball.png',
    ),
    EmojiPackItem(
      id: 'p_04',
      name: 'Cocktail Spill',
      category: EmojiCategory.party,
      tags: ['drink', 'funny'],
      gifQuery: 'cocktail spill funny',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'p_05',
      name: 'Confetti Cannon',
      category: EmojiCategory.party,
      tags: ['party', 'fun'],
      path: 'assets/emojis/party/confetti.png',
    ),
    EmojiPackItem(
      id: 'p_06',
      name: 'Clinking Glasses',
      category: EmojiCategory.party,
      tags: ['cheers', 'funny'],
      gifQuery: 'clinking glasses cheers',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'p_07',
      name: 'Beer Splash',
      category: EmojiCategory.party,
      tags: ['funny', 'drinks'],
      path: 'assets/emojis/party/beer_splash.png',
    ),
    EmojiPackItem(
      id: 'p_08',
      name: 'Mic Drop',
      category: EmojiCategory.party,
      tags: ['funny', 'wow'],
      path: 'assets/emojis/party/mic_drop.png',
    ),
    EmojiPackItem(
      id: 'p_09',
      name: 'Party Hat',
      category: EmojiCategory.party,
      tags: ['party', 'celebration'],
      path: 'assets/emojis/party/party_hat.png',
    ),
    EmojiPackItem(
      id: 'p_10',
      name: 'DJ Spin',
      category: EmojiCategory.party,
      tags: ['music', 'fun'],
      path: 'assets/emojis/party/dj_spin.png',
    ),
    EmojiPackItem(
      id: 'p_11',
      name: 'Dance Duo',
      category: EmojiCategory.party,
      tags: ['dance', 'fun'],
      path: 'assets/emojis/party/dance_duo.png',
    ),
    EmojiPackItem(
      id: 'p_12',
      name: 'Confetti Shower',
      category: EmojiCategory.party,
      tags: ['party', 'celebration'],
      gifQuery: 'confetti shower celebration',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'p_13',
      name: 'Balloon Pop',
      category: EmojiCategory.party,
      tags: ['party', 'fun'],
      path: 'assets/emojis/party/balloon_pop.png',
    ),
    EmojiPackItem(
      id: 'p_14',
      name: 'Champagne Fizz',
      category: EmojiCategory.party,
      tags: ['drink', 'celebration'],
      path: 'assets/emojis/party/champagne_fizz.png',
    ),
    EmojiPackItem(
      id: 'p_15',
      name: 'Salsa Dance',
      category: EmojiCategory.party,
      tags: ['dance', 'fun'],
      path: 'assets/emojis/party/salsa_dance.png',
    ),
    EmojiPackItem(
      id: 'p_16',
      name: 'Crowd Cheering',
      category: EmojiCategory.party,
      tags: ['fun', 'celebration'],
      gifQuery: 'crowd cheering celebration',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'p_17',
      name: 'Dance Fail',
      category: EmojiCategory.party,
      tags: ['funny', 'fail'],
      path: 'assets/emojis/party/dance_fail.png',
    ),
    EmojiPackItem(
      id: 'p_18',
      name: 'Party Jump',
      category: EmojiCategory.party,
      tags: ['party', 'fun'],
      path: 'assets/emojis/party/party_jump.png',
    ),
    EmojiPackItem(
      id: 'p_19',
      name: 'Limbo',
      category: EmojiCategory.party,
      tags: ['dance', 'funny'],
      path: 'assets/emojis/party/limbo.png',
    ),
    EmojiPackItem(
      id: 'p_20',
      name: 'Music Notes',
      category: EmojiCategory.party,
      tags: ['party', 'music'],
      path: 'assets/emojis/party/music_notes.png',
    ),

    // ── Meme (18+) ──────────────────────────────────────────────────────────
    EmojiPackItem(
      id: 'm_01',
      name: 'Rolling Laugh',
      category: EmojiCategory.meme,
      tags: ['laugh', 'funny'],
      path: 'assets/emojis/meme/rolling_laugh.png',
    ),
    EmojiPackItem(
      id: 'm_02',
      name: 'Mind Blown',
      category: EmojiCategory.meme,
      tags: ['shock', 'funny'],
      gifQuery: 'mind blown reaction',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'm_03',
      name: 'Dead Laugh',
      category: EmojiCategory.meme,
      tags: ['funny', 'meme'],
      path: 'assets/emojis/meme/dead_laugh.png',
    ),
    EmojiPackItem(
      id: 'm_04',
      name: 'Melting Face',
      category: EmojiCategory.meme,
      tags: ['funny', 'embarrassed'],
      path: 'assets/emojis/meme/melting_face.png',
    ),
    EmojiPackItem(
      id: 'm_05',
      name: 'Cartoon Curse',
      category: EmojiCategory.meme,
      tags: ['funny', 'rage'],
      path: 'assets/emojis/meme/cartoon_curse.png',
    ),
    EmojiPackItem(
      id: 'm_06',
      name: 'Chicken Strut',
      category: EmojiCategory.meme,
      tags: ['funny', 'silly'],
      path: 'assets/emojis/meme/chicken_strut.png',
    ),
    EmojiPackItem(
      id: 'm_07',
      name: 'Smiling Poop',
      category: EmojiCategory.meme,
      tags: ['funny', 'meme'],
      path: 'assets/emojis/meme/poop.png',
    ),
    EmojiPackItem(
      id: 'm_08',
      name: 'Ghost Flirty',
      category: EmojiCategory.meme,
      tags: ['fun', 'flirt'],
      path: 'assets/emojis/meme/ghost_flirty.png',
    ),
    EmojiPackItem(
      id: 'm_09',
      name: 'Ice Cube Fail',
      category: EmojiCategory.meme,
      tags: ['funny', 'slapstick'],
      path: 'assets/emojis/meme/ice_cube_fail.png',
    ),
    EmojiPackItem(
      id: 'm_10',
      name: 'Yo-Yo Fail',
      category: EmojiCategory.meme,
      tags: ['funny', 'fail'],
      path: 'assets/emojis/meme/yo_yo_fail.png',
    ),
    EmojiPackItem(
      id: 'm_11',
      name: 'Facepalm',
      category: EmojiCategory.meme,
      tags: ['fail', 'funny'],
      path: 'assets/emojis/meme/facepalm.png',
    ),
    EmojiPackItem(
      id: 'm_12',
      name: 'Shock Gasp',
      category: EmojiCategory.meme,
      tags: ['shocked', 'funny'],
      path: 'assets/emojis/meme/shock_gasp.png',
    ),
    EmojiPackItem(
      id: 'm_13',
      name: 'Exaggerated Cry',
      category: EmojiCategory.meme,
      tags: ['sad', 'funny'],
      path: 'assets/emojis/meme/exaggerated_cry.png',
    ),
    EmojiPackItem(
      id: 'm_14',
      name: 'Eye Roll',
      category: EmojiCategory.meme,
      tags: ['funny', 'annoyed'],
      path: 'assets/emojis/meme/eye_roll.png',
    ),
    EmojiPackItem(
      id: 'm_15',
      name: 'Cartoon Trip',
      category: EmojiCategory.meme,
      tags: ['funny', 'fail'],
      path: 'assets/emojis/meme/cartoon_trip.png',
    ),
    EmojiPackItem(
      id: 'm_16',
      name: 'Awkward Smile',
      category: EmojiCategory.meme,
      tags: ['funny', 'awkward'],
      path: 'assets/emojis/meme/awkward_smile.png',
    ),
    EmojiPackItem(
      id: 'm_17',
      name: 'Laugh Cry',
      category: EmojiCategory.meme,
      tags: ['funny', 'laugh'],
      gifQuery: 'laugh cry emoji funny',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'm_18',
      name: 'Sweating Nervous',
      category: EmojiCategory.meme,
      tags: ['nervous', 'funny'],
      path: 'assets/emojis/meme/sweat_nervous.png',
    ),
    EmojiPackItem(
      id: 'm_19',
      name: 'Cartoon Slap',
      category: EmojiCategory.meme,
      tags: ['slapstick', 'funny'],
      path: 'assets/emojis/meme/cartoon_slap.png',
    ),
    EmojiPackItem(
      id: 'm_20',
      name: 'Dizzy Stars',
      category: EmojiCategory.meme,
      tags: ['funny', 'dizzy'],
      path: 'assets/emojis/meme/dizzy_stars.png',
    ),

    // ── Romantic ─────────────────────────────────────────────────────────────
    EmojiPackItem(
      id: 'r_01',
      name: 'Heart Eyes',
      category: EmojiCategory.romantic,
      tags: ['love', 'flirt'],
      path: 'assets/emojis/romantic/heart_eyes.png',
    ),
    EmojiPackItem(
      id: 'r_02',
      name: 'Letter Love',
      category: EmojiCategory.romantic,
      tags: ['cute', 'funny'],
      path: 'assets/emojis/romantic/letter_love.png',
    ),
    EmojiPackItem(
      id: 'r_03',
      name: 'Awkward Hug',
      category: EmojiCategory.romantic,
      tags: ['funny', 'hug'],
      path: 'assets/emojis/romantic/awkward_hug.png',
    ),
    EmojiPackItem(
      id: 'r_04',
      name: 'Falling Rose',
      category: EmojiCategory.romantic,
      tags: ['romantic', 'funny'],
      gifQuery: 'falling rose romantic',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'r_05',
      name: 'Bed Bounce',
      category: EmojiCategory.romantic,
      tags: ['funny', 'suggestive'],
      path: 'assets/emojis/romantic/bed_bounce.png',
    ),
    EmojiPackItem(
      id: 'r_06',
      name: 'Cat Kiss',
      category: EmojiCategory.romantic,
      tags: ['cute', 'love'],
      path: 'assets/emojis/romantic/cat_kiss.png',
    ),
    EmojiPackItem(
      id: 'r_07',
      name: 'Heel Trip',
      category: EmojiCategory.romantic,
      tags: ['funny', 'fail'],
      path: 'assets/emojis/romantic/heel_trip.png',
    ),
    EmojiPackItem(
      id: 'r_08',
      name: 'Couple Pose',
      category: EmojiCategory.romantic,
      tags: ['funny', 'love'],
      path: 'assets/emojis/romantic/couple_pose.png',
    ),
    EmojiPackItem(
      id: 'r_09',
      name: 'Heart Balloon',
      category: EmojiCategory.romantic,
      tags: ['love', 'cute'],
      path: 'assets/emojis/romantic/heart_balloon.png',
    ),
    EmojiPackItem(
      id: 'r_10',
      name: 'Wink Kiss',
      category: EmojiCategory.romantic,
      tags: ['flirt', 'romantic'],
      path: 'assets/emojis/romantic/wink_kiss.png',
    ),
    EmojiPackItem(
      id: 'r_11',
      name: 'Flirty Look',
      category: EmojiCategory.romantic,
      tags: ['flirt', 'funny'],
      path: 'assets/emojis/romantic/flirty_look.png',
    ),
    EmojiPackItem(
      id: 'r_12',
      name: 'Blowing Heart',
      category: EmojiCategory.romantic,
      tags: ['love', 'cute'],
      gifQuery: 'blowing heart love cute',
      isGif: true,
    ),
    EmojiPackItem(
      id: 'r_13',
      name: 'Hug Emoji',
      category: EmojiCategory.romantic,
      tags: ['love', 'hug'],
      path: 'assets/emojis/romantic/hug_emoji.png',
    ),
    EmojiPackItem(
      id: 'r_14',
      name: 'Smooch',
      category: EmojiCategory.romantic,
      tags: ['love', 'funny'],
      path: 'assets/emojis/romantic/smooch.png',
    ),
    EmojiPackItem(
      id: 'r_15',
      name: 'Awkward Kiss',
      category: EmojiCategory.romantic,
      tags: ['funny', 'love'],
      path: 'assets/emojis/romantic/awkward_kiss.png',
    ),
    EmojiPackItem(
      id: 'r_16',
      name: 'Falling Cupid',
      category: EmojiCategory.romantic,
      tags: ['love', 'cute'],
      path: 'assets/emojis/romantic/falling_cupid.png',
    ),
    EmojiPackItem(
      id: 'r_17',
      name: 'Heart Pulse',
      category: EmojiCategory.romantic,
      tags: ['love', 'funny'],
      path: 'assets/emojis/romantic/heart_pulse.png',
    ),
    EmojiPackItem(
      id: 'r_18',
      name: 'Love Letter',
      category: EmojiCategory.romantic,
      tags: ['love', 'cute'],
      path: 'assets/emojis/romantic/love_letter.png',
    ),
    EmojiPackItem(
      id: 'r_19',
      name: 'Heart Pop',
      category: EmojiCategory.romantic,
      tags: ['funny', 'love'],
      path: 'assets/emojis/romantic/heart_pop.png',
    ),
    EmojiPackItem(
      id: 'r_20',
      name: 'Blushing Kiss',
      category: EmojiCategory.romantic,
      tags: ['flirty', 'cute'],
      path: 'assets/emojis/romantic/blushing_kiss.png',
    ),

    // ── Gestures ─────────────────────────────────────────────────────────────
    EmojiPackItem(
      id: 'g_01',
      name: 'Shrug',
      category: EmojiCategory.gesture,
      tags: ['funny', 'shrug'],
      path: 'assets/emojis/gesture/shrug_exaggerated.png',
    ),
    EmojiPackItem(
      id: 'g_02',
      name: 'Upside-down Grin',
      category: EmojiCategory.gesture,
      tags: ['funny', 'silly'],
      path: 'assets/emojis/gesture/upside_down_grin.png',
    ),
    EmojiPackItem(
      id: 'g_03',
      name: 'Side-eye',
      category: EmojiCategory.gesture,
      tags: ['funny', 'side-eye'],
      path: 'assets/emojis/gesture/side_eye_skeptical.png',
    ),
    EmojiPackItem(
      id: 'g_04',
      name: 'Shush',
      category: EmojiCategory.gesture,
      tags: ['funny', 'shush'],
      path: 'assets/emojis/gesture/shush_comical.png',
    ),
    EmojiPackItem(
      id: 'g_05',
      name: 'Salute Fail',
      category: EmojiCategory.gesture,
      tags: ['funny', 'salute'],
      path: 'assets/emojis/gesture/salute_fail.png',
    ),
    EmojiPackItem(
      id: 'g_06',
      name: 'Heart Hands',
      category: EmojiCategory.gesture,
      tags: ['cute', 'funny'],
      path: 'assets/emojis/gesture/heart_hands_big.png',
    ),
    EmojiPackItem(
      id: 'g_07',
      name: 'Pinch Face',
      category: EmojiCategory.gesture,
      tags: ['funny', 'small'],
      path: 'assets/emojis/gesture/pinch_face.png',
    ),
    EmojiPackItem(
      id: 'g_08',
      name: 'Peek Peek',
      category: EmojiCategory.gesture,
      tags: ['funny', 'peek'],
      path: 'assets/emojis/gesture/peek_peek_peek.png',
    ),
    EmojiPackItem(
      id: 'g_09',
      name: 'Melt Embarrassed',
      category: EmojiCategory.gesture,
      tags: ['funny', 'melt'],
      path: 'assets/emojis/gesture/melting_embarrassed.png',
    ),
    EmojiPackItem(
      id: 'g_10',
      name: 'Mouth Zipped',
      category: EmojiCategory.gesture,
      tags: ['secret', 'funny'],
      path: 'assets/emojis/gesture/mouth_zipped.png',
    ),
    EmojiPackItem(
      id: 'g_11',
      name: 'Facepalm',
      category: EmojiCategory.gesture,
      tags: ['funny', 'fail'],
      path: 'assets/emojis/gesture/facepalm.png',
    ),
    EmojiPackItem(
      id: 'g_12',
      name: 'Eye Roll',
      category: EmojiCategory.gesture,
      tags: ['funny', 'annoyed'],
      path: 'assets/emojis/gesture/eye_roll.png',
    ),
    EmojiPackItem(
      id: 'g_13',
      name: 'Fingers Crossed',
      category: EmojiCategory.gesture,
      tags: ['funny', 'hope'],
      path: 'assets/emojis/gesture/fingers_crossed.png',
    ),
    EmojiPackItem(
      id: 'g_14',
      name: 'Nose Scrunch',
      category: EmojiCategory.gesture,
      tags: ['funny', 'silly'],
      path: 'assets/emojis/gesture/nose_scrunch.png',
    ),
    EmojiPackItem(
      id: 'g_15',
      name: 'Big Grin',
      category: EmojiCategory.gesture,
      tags: ['funny', 'happy'],
      path: 'assets/emojis/gesture/big_grin.png',
    ),
    EmojiPackItem(
      id: 'g_16',
      name: 'Tongue Out',
      category: EmojiCategory.gesture,
      tags: ['silly', 'funny'],
      path: 'assets/emojis/gesture/tongue_out.png',
    ),
    EmojiPackItem(
      id: 'g_17',
      name: 'Side Wiggle',
      category: EmojiCategory.gesture,
      tags: ['silly', 'funny'],
      path: 'assets/emojis/gesture/side_wiggle.png',
    ),
    EmojiPackItem(
      id: 'g_18',
      name: 'Jazz Hands',
      category: EmojiCategory.gesture,
      tags: ['funny', 'silly'],
      path: 'assets/emojis/gesture/jazz_hands.png',
    ),
    EmojiPackItem(
      id: 'g_19',
      name: 'Thumbs Up',
      category: EmojiCategory.gesture,
      tags: ['funny', 'approve'],
      path: 'assets/emojis/gesture/thumbs_up.png',
    ),
    EmojiPackItem(
      id: 'g_20',
      name: 'Oh No',
      category: EmojiCategory.gesture,
      tags: ['funny', 'fail'],
      path: 'assets/emojis/gesture/oh_no.png',
    ),
  ];

  /// All items in [category].
  static List<EmojiPackItem> byCategory(EmojiCategory category) =>
      all.where((e) => e.category == category).toList(growable: false);

  /// Items whose name or tags contain [query] (case-insensitive).
  static List<EmojiPackItem> search(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return all;
    return all
        .where((e) {
          return e.name.toLowerCase().contains(q) ||
              e.tags.any((t) => t.contains(q));
        })
        .toList(growable: false);
  }
}



