import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mixvy/shared/models/room.dart';
import '../services/category_service.dart';
import '../services/room_service.dart';

/// Provider for CategoryService instance
final categoryServiceProvider = Provider<CategoryService>((ref) {
  return CategoryService();
});

/// Provider for RoomService instance
final roomServiceProvider = Provider<RoomService>((ref) {
  return RoomService(
    firestore: FirebaseFirestore.instance,
    categoryService: ref.watch(categoryServiceProvider),
  );
});

/// Provider for all available categories
final categoriesProvider = Provider<List<String>>((ref) {
  final categoryService = ref.watch(categoryServiceProvider);
  return categoryService.getAllCategories();
});

/// Provider for fetching all rooms as a stream
final allRoomsProvider = StreamProvider<List<Room>>((ref) {
  final roomService = ref.watch(roomServiceProvider);
  return roomService.fetchAllRooms();
});

/// Provider for fetching live rooms as a stream
final liveRoomsProvider = StreamProvider<List<Room>>((ref) {
  final roomService = ref.watch(roomServiceProvider);
  return roomService.fetchLiveRooms();
});

/// Family provider for fetching rooms by category
final roomsByCategoryProvider =
    StreamProvider.family<List<Room>, String>((ref, category) {
  final roomService = ref.watch(roomServiceProvider);
  return roomService.fetchRoomsByCategory(category);
});

/// Family provider for fetching rooms by host ID
final roomsByHostProvider =
    StreamProvider.family<List<Room>, String>((ref, hostId) {
  final roomService = ref.watch(roomServiceProvider);
  return roomService.fetchRoomsByHost(hostId);
});

/// Family provider for fetching a single room by ID
final roomByIdProvider =
    FutureProvider.family<Room?, String>((ref, roomId) async {
  final roomService = ref.watch(roomServiceProvider);
  return roomService.fetchRoomById(roomId);
});

/// Family provider for searching rooms by tags
final roomsByTagsProvider =
    StreamProvider.family<List<Room>, List<String>>((ref, tags) {
  final roomService = ref.watch(roomServiceProvider);
  return roomService.searchRoomsByTags(tags);
});

/// State notifier for creating rooms
class CreateRoomNotifier extends AsyncNotifier<Room?> {
  @override
  Future<Room?> build() async {
    return null;
  }

  /// Creates a new room with the given parameters
  Future<void> createRoom({
    required String title,
    required String description,
    required String hostId,
    required List<String> tags,
  }) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final roomService = ref.read(roomServiceProvider);

      final room = Room(
        id: '', // Will be generated by Firestore
        title: title,
        description: description,
        hostId: hostId,
        tags: tags,
        category: '', // Will be computed by service
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        isLive: false,
        viewerCount: 0,
      );

      final createdRoom = await roomService.createRoom(room);
      return createdRoom;
    });
  }

  /// Resets the state to null
  void reset() {
    state = const AsyncData(null);
  }
}

/// Provider for CreateRoomNotifier
final createRoomProvider = AsyncNotifierProvider<CreateRoomNotifier, Room?>(() {
  return CreateRoomNotifier();
});

/// State notifier for updating rooms
class UpdateRoomNotifier extends AsyncNotifier<void> {
  @override
  Future<void> build() async {}

  /// Updates an existing room
  Future<void> updateRoom(Room room) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final roomService = ref.read(roomServiceProvider);
      await roomService.updateRoom(room);
    });
  }

  /// Updates the live status of a room
  Future<void> updateLiveStatus(String roomId, bool isLive) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final roomService = ref.read(roomServiceProvider);
      await roomService.updateLiveStatus(roomId, isLive);
    });
  }

  /// Increments the viewer count
  Future<void> incrementViewerCount(String roomId) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final roomService = ref.read(roomServiceProvider);
      await roomService.incrementViewerCount(roomId);
    });
  }

  /// Decrements the viewer count
  Future<void> decrementViewerCount(String roomId) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final roomService = ref.read(roomServiceProvider);
      await roomService.decrementViewerCount(roomId);
    });
  }
}

/// Provider for UpdateRoomNotifier
final updateRoomProvider = AsyncNotifierProvider<UpdateRoomNotifier, void>(() {
  return UpdateRoomNotifier();
});

/// State notifier for deleting rooms
class DeleteRoomNotifier extends AsyncNotifier<void> {
  @override
  Future<void> build() async {}

  /// Deletes a room by ID (requires authorization)
  Future<void> deleteRoom(String roomId, String currentUserId) async {
    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final roomService = ref.read(roomServiceProvider);
      await roomService.deleteRoom(roomId, currentUserId);
    });
  }
}

/// Provider for DeleteRoomNotifier
final deleteRoomProvider = AsyncNotifierProvider<DeleteRoomNotifier, void>(() {
  return DeleteRoomNotifier();
});

